version: '3.5'

services:

  openvpn-server:
    build: .
    environment:
      - PUBLIC_CONNECTION_URL=udp://192.168.20.23:1194
      - PUSH_CLIENT_ROUTE=10.0.0.0 255.0.0.0
    network_mode: host
    privileged: true
